refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d: %H:%M:%S%.6f)} {h({l}):<5.5} - {M}: {m}{n}"
  rolling_file:
    kind: rolling_file
    path: logs/antiProbeCore.log
    append: true
    encoder:
      pattern: "{d(%Y-%m-%d: %H:%M:%S%.6f)} {h({l}):<5.5} - {M}: {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        pattern: logs/monster_hunter.{}.log
        base: 1
        count: 5
root:
  level: info
  appenders:
    - stdout
    - rolling_file
